-- ============================================
-- HEADSTONE LEGACY - SAMPLE DATA
-- Migration 003 - Optional sample data for testing
-- ============================================

-- Benjamin Franklin memorial (example/demo data)
INSERT INTO memorials (id, name, title, birth_date, death_date, story, cemetery_name, cemetery_address, cemetery_lat, cemetery_lng, location_lat, location_lng, is_location_exact, tier, status, main_photo, candle_count, created_at, updated_at) VALUES ('benjamin-franklin-founding-father', 'Benjamin Franklin', 'Founding Father, Scientist, Inventor, Diplomat & Statesman', '1706-01-17', '1790-04-17', 'Benjamin Franklin (January 17, 1706 - April 17, 1790) was one of the most influential Founding Fathers of the United States. Born on Milk Street in Boston, he was the 15th of 17 children. Despite only two years of formal education, his curiosity shaped him into one of the most learned men of his era. He established a printing house in Philadelphia in 1728, published Poor Richards Almanack in 1732, and made groundbreaking scientific discoveries including proving lightning was electrical. He founded the Library Company of Philadelphia, the American Philosophical Society, the University of Pennsylvania, and Philadelphias first fire department. Franklin was the only Founding Father to sign all four major documents: the Declaration of Independence, Treaty of Alliance with France, Treaty of Paris, and the Constitution. He served as Ambassador to France and President of Pennsylvania. He died at age 84 and over 20,000 people attended his funeral.', 'Christ Church Burial Ground', '340 N 5th St, Philadelphia, PA 19106', 39.9525394, -75.14831, 39.9525394, -75.14831, true, 'historian', 'published', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Joseph_Duplessis_-_Benjamin_Franklin_-_Google_Art_Project.jpg/800px-Joseph_Duplessis_-_Benjamin_Franklin_-_Google_Art_Project.jpg', 0, NOW(), NOW()) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, title = EXCLUDED.title, story = EXCLUDED.story, tier = EXCLUDED.tier, status = EXCLUDED.status, updated_at = NOW();

-- Update relatives
UPDATE memorials SET relatives = '[{"name":"Deborah Read Franklin","relationship":"Spouse","dates":"1708-1774","memorialId":""},{"name":"William Franklin","relationship":"Son","dates":"1730-1813","memorialId":""},{"name":"Francis Folger Franklin","relationship":"Son","dates":"1732-1736","memorialId":""},{"name":"Sarah Franklin Bache","relationship":"Daughter","dates":"1744-1808","memorialId":""},{"name":"Josiah Franklin","relationship":"Father","dates":"1657-1745","memorialId":""},{"name":"Abiah Folger Franklin","relationship":"Mother","dates":"1667-1752","memorialId":""}]'::jsonb WHERE id = 'benjamin-franklin-founding-father';

-- Update milestones
UPDATE memorials SET milestones = '[{"title":"Born in Boston","year":"1706","description":"Born on Milk Street"},{"title":"Apprentice Printer","year":"1718","description":"Apprentice to brother James"},{"title":"Moved to Philadelphia","year":"1723","description":"Left Boston at age 17"},{"title":"Printing House","year":"1728","description":"Established his own business"},{"title":"Married","year":"1730","description":"Married Deborah Read"},{"title":"Library Company","year":"1731","description":"Founded first subscription library"},{"title":"Poor Richards Almanack","year":"1732","description":"First publication"},{"title":"Fire Company","year":"1736","description":"Founded first fire department"},{"title":"Philosophical Society","year":"1743","description":"Founded scientific organization"},{"title":"University of PA","year":"1749","description":"Founded university"},{"title":"Kite Experiment","year":"1752","description":"Proved lightning is electrical"},{"title":"Postmaster General","year":"1753","description":"Appointed to postal system"},{"title":"Declaration","year":"1776","description":"Signed Declaration of Independence"},{"title":"Ambassador","year":"1778","description":"Ambassador to France"},{"title":"Treaty of Paris","year":"1783","description":"Ended Revolutionary War"},{"title":"PA President","year":"1785","description":"President of Pennsylvania"},{"title":"Constitution","year":"1787","description":"Signed US Constitution"},{"title":"Died","year":"1790","description":"Died April 17 in Philadelphia"}]'::jsonb WHERE id = 'benjamin-franklin-founding-father';

-- Update residences
UPDATE memorials SET residences = '[{"address":"Milk Street, Boston, MA","startYear":"1706","endYear":"1723"},{"address":"Philadelphia, PA","startYear":"1723","endYear":"1757"},{"address":"London, England","startYear":"1757","endYear":"1762"},{"address":"Philadelphia, PA","startYear":"1762","endYear":"1764"},{"address":"London, England","startYear":"1764","endYear":"1775"},{"address":"Paris, France","startYear":"1776","endYear":"1785"},{"address":"Philadelphia, PA","startYear":"1785","endYear":"1790"}]'::jsonb WHERE id = 'benjamin-franklin-founding-father';

-- Sample project notes
INSERT INTO project_notes (title, category, content, tags, is_pinned) VALUES
('Project Kickoff', 'decision', 'Migrated from Firebase to Supabase + Vercel. Focus on building engagement features next.', ARRAY['migration', 'supabase', 'vercel'], true),
('Feature Priority', 'feature', 'Phase 1: Virtual candles, Anniversary reminders, Enhanced tributes. Phase 2: Voice recordings, Video tributes, Life timeline.', ARRAY['roadmap', 'features'], true)
ON CONFLICT DO NOTHING;
